#ifndef __femus_enums_PrecondtypeEnum_hpp__
#define __femus_enums_PrecondtypeEnum_hpp__

enum PreconditionerType {
    IDENTITY_PRECOND =0,
    JACOBI_PRECOND,
    BLOCK_JACOBI_PRECOND,
    SOR_PRECOND,
    SSOR_PRECOND,
    EISENSTAT_PRECOND,
    ASM_PRECOND, //equivalent to ASM_MULTIPLICATIVE_PRECOND 
    ASM_ADDITIVE_PRECOND, 
    ASM_MULTIPLICATIVE_PRECOND, 
    CHOLESKY_PRECOND,
    ICC_PRECOND,
    ILU_PRECOND,
    LU_PRECOND,
    USER_PRECOND,
    SHELL_PRECOND,
    AMG_PRECOND,
    INVALID_PRECONDITIONER,
    MG_PRECOND,
    SLU_PRECOND,
    MLU_PRECOND,
    ULU_PRECOND,
    MCC_PRECOND,
    FIELDSPLIT_PRECOND, // equivalent to FIELDSPLIT_ADDITIVE_PRECOND
    FIELDSPLIT_ADDITIVE_PRECOND, 
    FIELDSPLIT_MULTIPLICATIVE_PRECOND, 
    FIELDSPLIT_SYMMETRIC_MULTIPLICATIVE_PRECOND, 
    FIELDSPLIT_SCHUR_PRECOND, 
    LSC_PRECOND
};



#endif
